language: scala

services:
  - docker

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test jdk11 2.13
      scala: 2.13.0
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION flutterby-core/test flutterby-cats_2_x/test
    - name: test jdk8 2.13
      scala: 2.13.0
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION flutterby-core/test flutterby-cats_2_x/test
    - name: test jdk11 2.12
      scala: 2.12.9
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test jdk8 2.12
      scala: 2.12.9
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt