language: scala

services:
  - docker

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test jdk11 3.0
      scala: 3.0.0-RC1
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test jdk8 3.0
      scala: 3.0.0-M3
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION test
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt