addSbtPlugin("com.github.gseitz"         % "sbt-release"               % "1.0.13")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"              % "3.9.3")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"                   % "2.0.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.12")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"    % "1.2.2")
