addSbtPlugin("com.github.gseitz"         % "sbt-release"               % "1.0.13")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"              % "3.9.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.3.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.8")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.11")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"    % "1.2.1")
